### ISSUE TITLE
Using binary files with node_encrypt always leads to content: content changed '<<encrypted>>' to '<<encrypted>>' message

### ISSUE THREAD

**Issue by olifre** [binford2k/binford2k-node_encrypt#24]
Luckily, contents seem to be fine, though. 
Using the classic `file` resource, this does not happen. 

Easy reproducer:
```
dd if=/dev/urandom of=someKeyFile.key bs=1 count=1000
```
Then a basic example such as:
```
                node_encrypt::file { "/etc/krb5.keytab":
                        mode    => '0400',
                        content => file("${module_name}/hostkeytabs/someKeyFile.key"),
                }
```
will trigger the notice. 
Observed for example with Kerberos V Keytab files, not observed with normal ASCII files (such as Certificates + Keys). 

The notice is a bit annoying if a tool to monitor actual changes (such as Foreman) is in use.

**Comment by binford2k** [comment]
oh, that must be infuriating. I'll make some time this or next week to track it down.

**Comment by olifre** [comment]
Dear @binford2k , 
did you already have time to look into it? 
Let me know if I can help and / or test, sadly, I don't have a good idea for a workaround off the top of my head.

**Comment by brwyatt** [comment]
I have a case where this was also happening to me even using the basic `file` resource. This could be due to some changes between Puppet versions, I'm using `4.10.9`.

I'm currently looking into simple "fixes" for this issue, but it looks like this doesn't expose the `checksum_value` file attribute. I'm going to add this and issue a pull request. At least that would allow for a workaround to settle the Puppet reports (or prevent possible service restarts for some manifests) until this can be more properly fixed.

**Comment by brwyatt** [comment]
Actually, scratch that. Since the comparison is done within the Ruby code of this module for the `node_encrypt::file` type (rather than by the `file` type itself), what I was suggesting won't work. And, looking at where I think you are making the comparison, I don't really see a good way that I would be able to (easily) make what I was thinking about work in this context.

So much for a lazy quick workaround...
